# Generated by Django 6.0.3 on 2026-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=13)),
                ('Course', models.CharField(max_length=255)),
                ('Date_of_Admission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
